config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :genres
  resources :artists

  get '/', to: 'application#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :songs
	has_many :genres, through: :songs
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :songs
	has_many :artists, through: :songs
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :genre
	belongs_to :artist
	accepts_nested_attributes_for :artist

	def genre_name=(name)
		self.genre = Genre.find_or_create_by(name: name)
	end

	def genre_name
		self.genre ? self.genre.name : nil
	end

	def artist_name=(name)
		self.artist = Artist.find_or_create_by(name: name)
	end

	def artist_name
		self.artist ? self.artist.name : nil
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def index
		render :home
	end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_action :find_artist, only: [:show, :edit, :update, :destroy]

	def index
		@artists = Artist.all
	end

	def new
		@artist = Artist.new
	end

	def create
		artist = Artist.create(artist_strong_params)
		redirect_to artist_path(artist)
	end

	def update
		@artist.update(artist_strong_params)
		redirect_to artist_path(@artist)
	end

	def destroy
		@artist.destroy
		redirect_to artists_path
	end

	private

		def find_artist
			@artist = Artist.find(params[:id])
		end

		def artist_strong_params
			params.require(:artist).permit(:name,
				song_attributes: [:name, :artist_id, :genre_id])
		end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
	before_action :find_genre, only: [:show, :edit, :update, :destroy]

	def index
		@genres = Genre.all
	end

	def new
		@genre = Genre.new
	end

	def create
		genre = Genre.create(genre_strong_params)
		redirect_to genre_path(genre)
	end

	def update
		@genre.update(genre_strong_params)
		redirect_to genre_path(@genre)
	end

	def destroy
		@genre.destroy
		redirect_to genres_path
	end

	private

		def find_genre
			@genre = Genre.find(params[:id])
		end

		def genre_strong_params
			params.require(:genre).permit(:name)
		end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    before_action :find_song, only: [:show, :edit, :update, :destroy]

	def index
		@songs = Song.all
	end

	def new
		@song = Song.new
    end
    
    def create
        artist = Artist.find_or_create_by(name: song_params[:artist_name])
        genre = Genre.find_or_create_by(name: song_params[:genre_name])
        @song = artist.songs.build(song_params)
        @song = genre.songs.build(song_params)
        @song.save!
        # byebug
        redirect_to song_path(@song)
    end
    
    # artist = Artist.find_or_create_by(name: song_params[:artist_name])
    # @song = artist.songs.build(song_params)

    # if @song.save
    #   redirect_to songs_path
    # else
    #   render :new
    # end

	def update
		@song.update(song_params)
		redirect_to song_path(@song)
	end

	def destroy
		@song.destroy
		redirect_to songs_path
	end

	private

		def find_song
			@song = Song.find(params[:id])
		end

        def song_params
            params.require(:song).permit(:name, :artist_name, :genre_name)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/application/home.html.erb
<h1>Welcome to Genrify™!</h1>
<p>Genrify is a purely conceptual music application. It is not inspired by anything in particular, <strong>we swear.</strong></p>
<p>All data was randomly generated using the <a href="https://github.com/faker-ruby" target="_blank">Faker gem.</a></p>
<p>Genrify was created by Kyle Cole and Matt Heavner at the <a href="https://flatironschool.com/" target="_blank">Flatiron School</a>.</p>

app/views/artists/_artist_form.html.erb
<%= form_for @artist do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.submit submit_text %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit <%= @artist.name %></h1>

<%= render partial: "artist_form", locals: {submit_text: "Edit Artist"} %>

app/views/artists/index.html.erb
<h1>All Artists</h1>
<%= button_to "Create Artist", new_artist_path, method: :get %>

<ul>
	<% @artists.each do |artist| %>
		<li><%= link_to artist.name, artist_path(artist) %></li>
	<% end %>
</ul>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render partial: "artist_form", locals: {submit_text: "Create a new Artist"} %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
	<%= button_to "Edit this Artist", edit_artist_path(@artist), method: :get %>
	<%= button_to "Delete this Artist", artist_path(@artist), method: :delete,
			data: { confirm: "Are you sure you'd like to delete #{@artist.name}"}%>

<h2>Songs</h2>
	<ul>
		<% @artist.songs.each do |song| %>
			<li><%= link_to song.name, song_path(song) %></li>
		<% end %>
	</ul>

<h2>Genres</h2>
	<ul>
		<% @artist.genres.each do |genre| %>
			<li><%= link_to genre.name, genre_path(genre) %></li>
		<% end %>
	</ul>

app/views/genres/_genre_form.html.erb
<%= form_for @genre do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.submit submit_text %>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit <%= @genre.name %></h1>

<%= render partial: "genre_form", locals: {submit_text: "Edit Genre"} %>

app/views/genres/index.html.erb
<h1>All Genres</h1>
<%= button_to "Create Genre", new_genre_path, method: :get %>


<ul>
	<% @genres.each do |genre| %>
		<li><%= link_to genre.name, genre_path(genre) %></li>
	<% end %>
</ul>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render partial: "genre_form", locals: {submit_text: "Create a new genre"} %>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<div>
	<%= button_to "Edit this Genre", edit_genre_path(@genre), method: :get %>
	<%= button_to "Delete this Genre", genre_path(@genre), method: :delete,
			data: { confirm: "Are you sure you'd like to delete #{@genre.name}"}%>
</div>

<h2>Genre by Artist & Songs</h2>
<ul>
	<% @genre.artists.each do |artist| %>
		<li><%= link_to artist.name, artist_path(artist) %></li>

		<!-- <h2>Songs</h2> -->
		<% genre_songs = artist.songs.select do |song| %>
				<% song.genre == @genre %>
		<% end %>

		<ul>
			<% genre_songs.each do |song| %>
				<li><%= link_to song.name, song_path(song) %></li>
			<% end %>
		</ul>

	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Genrify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <a href="/"><%= image_tag 'Genrify_Full_Black.png', style: 'width:35%;height:auto;' %></a>
    <!-- <h1>Welcome to Genrify™!</h1> -->
    <nav>
      <%= link_to "Browse by Song", songs_path %> /
      <%= link_to "Browse by Artist", artists_path %> /
      <%= link_to "Browse by Genre", genres_path %>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/songs/edit.html.erb
<br>
<h1>Edit Song</h1>
<%= form_for @song do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :artist_name %>
    <%= f.text_field :artist_name, list: "artists_autocomplete" %>
    <datalist id="artists_autocomplete">
        <% Artist.all.each do |artist| %>
            <option value="<%= artist.name %>">
        <% end %>
    </datalist>

    <%= f.label :genre_name %>
    <%= f.text_field :genre_name, list: "genres_autocomplete" %>
    <datalist id="genres_autocomplete">
        <% Genre.all.each do |genre| %>
            <option value="<%= genre.name %>">
        <% end %>
    </datalist>
    
    <%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<h1>All Songs</h1>
<%= button_to "Create Song", new_song_path, method: :get %>


    <ul>
    <% @songs.each do |song| %>
        <li><%= link_to song.name + " / " + song.artist.name, song_path(song) %></li>
    <% end %>
    </ul>

app/views/songs/new.html.erb
<br>
<h1>New Song</h1>
<%= form_for @song do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :artist_name %>
    <%= f.text_field :artist_name, list: "artists_autocomplete" %>
    <datalist id="artists_autocomplete">
        <% Artist.all.each do |artist| %>
            <option value="<%= artist.name %>">
        <% end %>
    </datalist>

    <%= f.label :genre_name %>
    <%= f.text_field :genre_name, list: "genres_autocomplete" %>
    <datalist id="genres_autocomplete">
        <% Genre.all.each do |genre| %>
            <option value="<%= genre.name %>">
        <% end %>
    </datalist>
    
    <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.name %></h1>
    <div>
        <%= button_to "Edit Song", edit_song_path(@song), method: :get %>
        <%= button_to "Delete Song", song_path(@song), method: :delete, data: {confirm: "Are you sure you'd like to delete #{@song.name}?"} %>
    </div>
    <div>
        <p>
            Artist: <%= link_to @song.artist.name, artist_path(@song.artist) %>
            &nbsp; Genre: <%= link_to @song.genre.name, genre_path(@song.genre) %>
        </p>
        <p>All of their songs:</p>
        <ul>
            <% Song.all.select do |song| %>
               <% song.artist == @song.artist %>
               <li><%= link_to song.name, song_path(song) %></li>
            <% end %>
        </ul>
    </div>